apiVersion: v1
kind: Service
metadata:
  name: simple-myapp-service
spec:
  type: NodePort
  selector:
    app: simple-myapp
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-myapp-deployment
  labels:
    app: simple-myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-myapp
  template:
    metadata:
      labels:
        app: simple-myapp
    spec:
      containers:
      - name: nginx
        image: apisit19122/simple-myapp
        ports:
        - containerPort: 80